# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(700, 400, 181, 161))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.NewLevelButton = QtWidgets.QPushButton(Form)
        self.NewLevelButton.setGeometry(QtCore.QRect(1150, 400, 181, 161))
        self.NewLevelButton.setText("")
        self.NewLevelButton.setObjectName("NewLevelButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
